apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogosv-server-deployment
  labels:
    app: catalogosv-server-deployment
spec:
  selector:
    matchLabels:
      app: catalogosv-server-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: catalogosv-server-deployment
    spec:
      containers:
        - name: catalogosv-server
          image: marcovcg1819/catalogosv-server:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: catalogosv-server-service
  labels:
    app: catalogosv-server-service
spec:
  selector:
    app: catalogosv-server-deployment
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
  type: LoadBalancer