server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
        default-filters:
          - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: ms-vehiculos
          uri: lb://ms-vehiculos
          predicates:
            - Path=/vehiculo/**
        - id: ms-vehrep
          uri: lb://ms-vehrep
          predicates:
            - Path=/vehrep/**
        - id: ms-costo
          uri: lb://ms-costo
          predicates:
            - Path=/costo/**
        - id: ms-reparaciones
          uri: lb://ms-reparaciones
          predicates:
            - Path=/reparacion/**
        - id: ms-tipo
          uri: lb://ms-tipo
          predicates:
            - Path=/tipo/**
