server:
  port: 8093
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reparaciones-db
    username: postgres
    password: 1234
eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/