apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogosr-server-deployment
  labels:
    app: catalogosr-server-deployment
spec:
  selector:
    matchLabels:
      app: catalogosr-server-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: catalogosr-server-deployment
    spec:
      containers:
        - name: catalogosr-server
          image: marcovcg1819/catalogosr-server:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: catalogosr-server-service
  labels:
    app: catalogosr-server-service
spec:
  selector:
    app: catalogosr-server-deployment
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: LoadBalancer